### ISSUE TITLE
师傅看看这是咋回事？

### ISSUE THREAD

**Issue by EVILELLY** [M0nster3/OneLong#2]
连着跑了两遍都会出现这个问题，是不是目标公司的域名太多了
![微信图片_20240404212905](https://github.com/M0nster3/OneLong/assets/53610499/5f27ef42-b7c7-4297-8bdf-68e7dcd6fca6)
![image](https://github.com/M0nster3/OneLong/assets/53610499/c665e9f3-40b9-4f37-ae5e-6a1ba73628d4)

panic: runtime error: slice bounds out of range [-1:]

goroutine 1 [running]:
OneLong/Script/Ehole.Ehole({0xc004bc8000, 0x1902, 0x1?}, 0xc0003d9b80, 0xc0001206c0)
        /Users/Monster/Tools/Go_work/OneLong/Script/Ehole/Ehole.go:17 +0x3b3
OneLong/Web/HttpZhiwen.Status({0xc0001580b0, 0xd}, 0xc0003d9b80, 0xc0001206c0)
        /Users/Monster/Tools/Go_work/OneLong/Web/HttpZhiwen/HttpZhiwen.go:65 +0x2fb
OneLong/Utils/Gogogo.DomainRunJob(0xc0003d9b80)
        /Users/Monster/Tools/Go_work/OneLong/Utils/Gogogo/Gogogo.go:210 +0x285
OneLong/Utils/Gogogo.StartScan(0xc0003d9b80)
        /Users/Monster/Tools/Go_work/OneLong/Utils/Gogogo/Gogogo.go:69 +0x1de
main.main()
        /Users/Monster/Tools/Go_work/OneLong/OneLong.go:13 +0x39

**Comment by M0nster3** [comment]
从新 下载代码编译一下

**Comment by EVILELLY** [comment]
好的，我试试。

**Comment by M0nster3** [comment]
我打包好了 直接下载吧
