### ISSUE TITLE
师傅，报错了，不太懂go

### ISSUE THREAD

**Issue by 10056789** [M0nster3/OneLong#3]
panic: runtime error: index out of range [0] with length 0

goroutine 17455 [running]:
OneLong/Script/Ehole/module/finger.(*FinScan).fingerScan(0xc0007a64d0, 0xc0007fcc80)
        /Users/Monster/Tools/Go_work/OneLong/Script/Ehole/module/finger/finger.go:176 +0x2c19
OneLong/Script/Ehole/module/finger.(*FinScan).StartScan.func1()
        /Users/Monster/Tools/Go_work/OneLong/Script/Ehole/module/finger/finger.go:65 +0x53
created by OneLong/Script/Ehole/module/finger.(*FinScan).StartScan in goroutine 1
        /Users/Monster/Tools/Go_work/OneLong/Script/Ehole/module/finger/finger.go:63 +0x2f

**Comment by M0nster3** [comment]
把代码从新下载一份 然后打包 之前我修复了 就是还没有集成打包传递到release里面
